# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElCartona' do
  pod 'AppCenter/Crashes', '~> 2.4.0'
  pod 'AppCenter/Analytics', '~> 2.4.0'
  pod 'AppCenterReactNativeShared', '~> 2.4.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElCartona

  
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'

  post_install do |installer|
    system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
  end
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  # post_install do |installer|
  #   rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
  #   rnfirebase.build_configurations.each do |config|
  #     config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
  #   end
  # end
  # pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'ElCartonaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ElCartona-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElCartona-tvOS

  target 'ElCartona-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
